### ISSUE TITLE
Error in deserialization

### ISSUE THREAD

**Issue by burdoto** [Aurasphere/jandex#2]
When executing the following code; I get an exception, which is supposedly a deserialization exception:
```java
        TRANSLATOR = new Jyandex(new BufferedReader(new FileReader(getFile("login/yandex-translate.cred")))
                .readLine());
        
        TranslateTextResponse response = TRANSLATOR.translateText("ohayou", Language.ENGLISH);

        System.out.println("response.getTranslatedText() = " + Arrays.toString(response.getTranslatedText()));
```
Project dependencies:
```groovy
dependencies {
    // Javacord
    implementation 'org.javacord:javacord:3.0.+'

    // Javacord Utilities
    //implementation('de.kaleidox:javacord-utilities:1.0.2rev1')
    //        { exclude group: 'org.javacord' }
    implementation('com.github.burdoto:javacord-utilities:dea7af816d')
            { exclude group: 'org.javacord' }

    // Other dependencies
    implementation 'co.aurasphere:jyandex:1.0.0'
    implementation 'com.fasterxml.jackson.core:jackson-databind:2.9.3'

    // Runtime logger dependency
    runtimeOnly 'org.apache.logging.log4j:log4j-core:2.11.0'

    // Annotations dependency
    compileOnly 'org.jetbrains:annotations:17.0.0'
}
```
The exception: 
```
Exception in thread "main" java.lang.NoSuchMethodError: com.fasterxml.jackson.databind.util.BeanUtil.okNameForSetter(Lcom/fasterxml/jackson/databind/introspect/AnnotatedMethod;)Ljava/lang/String;
	at com.fasterxml.jackson.module.jaxb.JaxbAnnotationIntrospector.findNameForDeserialization(JaxbAnnotationIntrospector.java:1008)
	at com.fasterxml.jackson.databind.introspect.AnnotationIntrospectorPair.findNameForDeserialization(AnnotationIntrospectorPair.java:749)
	at com.fasterxml.jackson.databind.introspect.POJOPropertiesCollector._addSetterMethod(POJOPropertiesCollector.java:620)
	at com.fasterxml.jackson.databind.introspect.POJOPropertiesCollector._addMethods(POJOPropertiesCollector.java:535)
	at com.fasterxml.jackson.databind.introspect.POJOPropertiesCollector.collectAll(POJOPropertiesCollector.java:309)
	at com.fasterxml.jackson.databind.introspect.POJOPropertiesCollector.getPropertyMap(POJOPropertiesCollector.java:287)
	at com.fasterxml.jackson.databind.introspect.POJOPropertiesCollector.getProperties(POJOPropertiesCollector.java:170)
	at com.fasterxml.jackson.databind.introspect.BasicBeanDescription._properties(BasicBeanDescription.java:164)
	at com.fasterxml.jackson.databind.introspect.BasicBeanDescription.findProperties(BasicBeanDescription.java:239)
	at com.fasterxml.jackson.databind.deser.BasicDeserializerFactory._findCreatorsFromProperties(BasicDeserializerFactory.java:361)
	at com.fasterxml.jackson.databind.deser.BasicDeserializerFactory._constructDefaultValueInstantiator(BasicDeserializerFactory.java:345)
	at com.fasterxml.jackson.databind.deser.BasicDeserializerFactory.findValueInstantiator(BasicDeserializerFactory.java:269)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerFactory.buildBeanDeserializer(BeanDeserializerFactory.java:214)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerFactory.createBeanDeserializer(BeanDeserializerFactory.java:137)
	at com.fasterxml.jackson.databind.deser.DeserializerCache._createDeserializer2(DeserializerCache.java:411)
	at com.fasterxml.jackson.databind.deser.DeserializerCache._createDeserializer(DeserializerCache.java:349)
	at com.fasterxml.jackson.databind.deser.DeserializerCache._createAndCache2(DeserializerCache.java:264)
	at com.fasterxml.jackson.databind.deser.DeserializerCache._createAndCacheValueDeserializer(DeserializerCache.java:244)
	at com.fasterxml.jackson.databind.deser.DeserializerCache.findValueDeserializer(DeserializerCache.java:142)
	at com.fasterxml.jackson.databind.DeserializationContext.findRootValueDeserializer(DeserializationContext.java:477)
	at com.fasterxml.jackson.databind.ObjectReader._prefetchRootDeserializer(ObjectReader.java:1938)
	at com.fasterxml.jackson.databind.ObjectReader.forType(ObjectReader.java:677)
	at com.fasterxml.jackson.databind.ObjectReader.withType(ObjectReader.java:718)
	at com.fasterxml.jackson.jaxrs.base.ProviderBase.readFrom(ProviderBase.java:804)
	at org.glassfish.jersey.message.internal.ReaderInterceptorExecutor$TerminalReaderInterceptor.invokeReadFrom(ReaderInterceptorExecutor.java:256)
	at org.glassfish.jersey.message.internal.ReaderInterceptorExecutor$TerminalReaderInterceptor.aroundReadFrom(ReaderInterceptorExecutor.java:235)
	at org.glassfish.jersey.message.internal.ReaderInterceptorExecutor.proceed(ReaderInterceptorExecutor.java:155)
	at org.glassfish.jersey.message.internal.MessageBodyFactory.readFrom(MessageBodyFactory.java:1085)
	at org.glassfish.jersey.message.internal.InboundMessageContext.readEntity(InboundMessageContext.java:874)
	at org.glassfish.jersey.message.internal.InboundMessageContext.readEntity(InboundMessageContext.java:808)
	at org.glassfish.jersey.client.ClientResponse.readEntity(ClientResponse.java:326)
	at org.glassfish.jersey.client.InboundJaxrsResponse$1.call(InboundJaxrsResponse.java:115)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:315)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:297)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:228)
	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:419)
	at org.glassfish.jersey.client.InboundJaxrsResponse.runInScopeIfPossible(InboundJaxrsResponse.java:267)
	at org.glassfish.jersey.client.InboundJaxrsResponse.readEntity(InboundJaxrsResponse.java:112)
	at co.aurasphere.jyandex.Jyandex.translateText(Jyandex.java:264)
	at co.aurasphere.jyandex.Jyandex.translateText(Jyandex.java:196)
	at de.kaleidox.BotToolkit.main(BotToolkit.java:80)
```

**Comment by burdoto** [comment]
After investigating the stacktrace, I have noticed this compiler warning:
![grafik](https://user-images.githubusercontent.com/42473485/59562542-24b13780-902e-11e9-9c88-60ee27f42360.png)

This figures to that this might be a version mismatch, since I am using the very latest version of Jackson Databind.

I will keep this issue updated about this error.

**Comment by burdoto** [comment]
This indeed is an incompatibility problem from `org.jackson.databind.core:2.9.9` to `2.5.4`, which is the dependency for the REST client.

With this dependency setup, I get a normal result:
```groovy
dependencies {
    // Javacord
    implementation('org.javacord:javacord:3.0.+') {
        exclude group: 'com.fasterxml.jackson.core'
    }

    // Javacord Utilities
    //implementation('de.kaleidox:javacord-utilities:1.0.2rev1')
    //        { exclude group: 'org.javacord' }
    implementation('com.github.burdoto:javacord-utilities:dea7af816d') { 
        exclude group: 'org.javacord'
        exclude group: 'com.fasterxml.jackson.core'
    }

    // Other dependencies
    implementation 'co.aurasphere:jyandex:1.0.0'
    implementation 'com.fasterxml.jackson.core:jackson-databind:2.5.4'

    // Runtime logger dependency
    runtimeOnly 'org.apache.logging.log4j:log4j-core:2.11.0'

    // Annotations dependency
    compileOnly 'org.jetbrains:annotations:17.0.0'
}
```

However, this solution is not optimal, since version `2.9.5` is used by the Javacord dependency.

I will open a PR updating to an up-to-date REST client later.
